### ISSUE TITLE
Thread models untested

### ISSUE THREAD

**Issue by connorjward** [connorjward/pyop3#17]
I am in the process of adding parallel to pyop3. To get the right behaviour for halo exchanges I have used Python's `threading` library. @JDBetteridge has pointed out that different systems support threading differently so I have added the configuration option `PYOP3_THREAD_MODEL` which can be `"SINGLE"`, `"SERIALIZED"` or `"MULTIPLE"`. These should all be tested in CI.

**Comment by wence-** [comment]
Is there a particular reason for threading in python. On the whole I would shy away from threading at all, but you don't get a lot of parallelism/background progress using threads in python unless your threads drop the gil most of the time.

**Comment by connorjward** [comment]
I have tried to implement an even lazier halo exchange where the local-to-global is also done lazily. This means that in the interleaved halo exchanges we may need to do a reduction followed by a broadcast. Using threads is my solution to doing this is a non-blocking fashion. I am not using threading for the actual computation and the GIL, I believe, shouldn't be an issue for this use case.

**Comment by wence-** [comment]
Ah OK. How does this background thread communicate to the main thread that it has "completed" the exchange, if that needs to happen?

**Comment by connorjward** [comment]
> Ah OK. How does this background thread communicate to the main thread that it has "completed" the exchange, if that needs to happen?

I'm using `thread.join()` which simply waits for the background thread to terminate. It's something like
```py
threads = [...]

# start halo exchanges
for t in threads:
    t.start()

# loop over core
...

# block until all threads terminate
for t in threads:
    t.join()

# loop over owned
...
```

**Comment by wence-** [comment]
Is this because you don't trust MPI background progress engines? With that pseudo-code, it's not clear to me what you're trying to parallelise with the background threads: everything funnels into the same MPI process.

I'd also be worried about race conditions in PETSc (which is not thread-safe in most circumstances) if multiple exchanges on different threads share the same SF.

**Comment by wence-** [comment]
> I believe that thread safety for PETSc should be fine because of the GIL.

This is a common misconception, and is _not true_.

What does the GIL guarantee? It guarantees that the _internal_ interpreter state is never inconsistent in the presence of threading. You can, to first order, think of it as a lock around the refcount of a python object. If an object is shared with two threads that means that the refcount can never incorrectly be one while both of them are live.

What does the GIL _not_ guarantee: that your code is free of data races (or even that python statements as written in your code are executed _atomically_). Even purely in Python code it is not the case that the GIL ensures that you are free of races (it's implemented in a time-sharing manner so every `X` ms, the interpreter on thread T release the GIL to see if someone else wants it). But with calls into PETSc, as soon as the cython wrapper makes the call into PETSc proper it drops the GIL, so it won't save you from possible data races inside PETSc.

**Comment by connorjward** [comment]
I see. I will look into this more. I thought I was being terribly clever with my threading solution but it may well not work.

**Comment by wence-** [comment]
If I understand your example you want (without the threading) to run something like:
```
array0.reduce_leaves_to_roots_begin()
array1.broadcast_roots_to_leaves_begin()
# loop over core
...
array0.reduce_leaves_to_roots_end()
array1.broadcast_roots_to_leaves_end()
array0.broadcast_roots_to_leaves_begin() # You want to post this one as soon as the array0.reduce has completed
array0.broadcast_roots_to_leaves_end()
# loop over owned
...
```

My first check would be (rather than trying to introduce threading): is that `array0.broadcast_xxx` a significant perf bottleneck.

**Comment by wence-** [comment]
To be concrete wrt petsc race conditions, for example. `PetscSFBcastBegin_Basic` calls `PetscSFLinkCreate` which tries to find a usable "communication link" for the given buffer/MPI_Datatype. Existing links are stored as a singly-linked list and if a suitable one isn't found then creates a new one. This search/modification is not thread safe. For example two threads calling `PetscSFLinkCreate` will do:
```
  for (p = &bas->avail; (link = *p); p = &link->next) {
      PetscCall(MPIPetsc_Type_compare(unit, link->unit, &match));
      if (match) {
        // link can be used, grab it
      }
      *p = link->next; /* Remove from available list */
```

But there's a race condition between checking the match to grab the link and removing it from the available list. So two threads could easily end up using the same link and bad things would happen.

**Comment by wence-** [comment]
You could handle this by having the shared thing (the SF) be guarded by a mutex. So you would do:

```
# This will protect access to `sf`
sf_lock = threading.Lock()
def bcast_begin(...):
    with sf_lock:
         sf.do_whatever(...)
def bcast_end(...):
    with sf_lock:
        ...
```

But generally, one should apply the first rule of threaded programming: "don't"

**Comment by connorjward** [comment]
Sure. Thank you very much for the feedback. I will get rid of the threading shortly.
